# GitHub Pages configuration for Audiobookshelf Cast Receiver Styles
title: Audiobookshelf Cast Receiver Styles
description: Custom CSS styling for Google Cast receivers, designed for Audiobookshelf audiobook playback
url: "https://cast.awsomefox.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/

# Include files that would normally be excluded
include:
  - .nojekyll

# Plugins
plugins:
  - jekyll-sitemap